services:
  - type: web
    name: agricultural-super-app-api
    env: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && gunicorn wsgi:app
    buildFilter:
      paths:
        - server/**
    preDeployCommand: cd server && python init_prod_db.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: wsgi.py
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: agricultural-super-app-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: agricultural-super-app-db
    databaseName: agricultural_super_app
    user: agricultural_super_app_user
    plan: free
