name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install Node.js dependencies
      run: |
        if [ -f package.json ]; then npm install; fi
        
    - name: Run full test suite
      run: |
        # Run Python tests
        if [ -d "tests" ]; then
          python -m pytest tests/ -v --cov
        fi
        
        # Run JavaScript tests
        if [ -f package.json ]; then
          npm test -- --coverage --watchAll=false
        fi
        
    - name: Build application for production
      run: |
        # Build React app for production
        if [ -f package.json ]; then
          npm run build
        fi
        
    - name: Deploy to Production
      run: |
        echo "🚀 Deploying to production environment..."
        echo "⚠️  Production deployment - please verify all tests passed"
        echo "✅ Production deployment completed successfully!"
        echo "🌐 Production URL: https://your-production-url.com"
        
    - name: Notify team of production deployment
      run: |
        echo "📢 PRODUCTION DEPLOYMENT NOTIFICATION:"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo "Author: ${{ github.actor }}"
        echo "🎉 Successfully deployed to PRODUCTION!"
        echo "🔍 Please monitor application for any issues"